# The URL the site will be built for
base_url = "https://mxasher.gay/"

author = "Asher Marrok"
title = "Asher's Site"
description = "Asher's little slice of internet"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Auto generate a sitemap.
generate_sitemap = true

[markdown]
external_links_target_blank = true
bottom_footnotes = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[[taxonomies]]
name = "tags"
feed = true

[extra]
# Put all your custom variables here
email = "asher@mxasher.gay"
license_name = "CC BY-NC 4.0"
license_link = "https://creativecommons.org/licenses/by-nc/4.0/"
copyright_years = "2026-2026"